{"rightSidebarLinks":[{"id":"exception-handling","title":"ExceptionHandlingAndLogging","subLink":null}],"title":"ExceptionHandlingAndLogging","description":"","validatorType":"decorators","validationTypeTitle":"Decorators","type":"simple","category":"security","subCategory":null,"linkTitle":"exceptionhandlingandlogging","tabArray":{},"innerHtml":{"m_MaxCapacity":2147483647,"Capacity":2352,"m_StringValue":"<p class='showHideElement' >Exception handling and logging keeps a trace of all the exceptions that occur whenever any request is made to the APIs. `IExceptionHandlerFeature` of Microsoft.AspNetCore.Diagnostics gives information about the error occured and the path. The error object of the same contains information of message, source, stacktrace and targetsite which provides the necessary information to detect the cause of the exception. Further the `LogAsync` method of `RxWeb.Core.Logging` will log the exception details in the database based upon the exception and the context.</p>\r\n<div highlight='pre code'><pre><code>\r\n        private static void HandleException(this IApplicationBuilder applicationBuilder)\r\n        {\r\n            applicationBuilder.UseExceptionHandler(errorApp =>\r\n            {\r\n                errorApp.Run(async context =>\r\n                {\r\n                    var errorFeature = context.Features.Get<IExceptionHandlerFeature>();\r\n                    var exception = errorFeature.Error;\r\n\t\t\t\t\tvar traceId = await exception.LogAsync(context);\r\n                    context.Response.ContentType = \"application/json;\";\r\n                    await context.Response.WriteAsync(\"Error Has Occured.\");\r\n                });\r\n            });\r\n        }\r\n</code></pre></div>\r\n","m_currentThread":0},"htmlContent":null}